name: optima_healthcare_mobile
description: Mobile app for OptimaHealthcare EHR
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  http: ^1.2.2
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  table_calendar: ^3.1.2
  web_socket_channel: ^3.0.2
  record: ^6.2.0
  permission_handler: ^11.3.1
  pdf: ^3.11.3
  printing: ^5.14.2
  video_player: ^2.9.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/video/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Padam_app.png"
