<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\OptimaHealthcare.Application.csproj" />
    <ProjectReference Include="..\Contracts\OptimaHealthcare.Contracts.csproj" />
    <ProjectReference Include="..\Domain\OptimaHealthcare.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
